export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const DELETE_SEARCH_HISTORY = 'DELETE_SEARCH_HISTORY'

export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'
